### ISSUE TITLE
disqus doesn't works.

### ISSUE THREAD

**Issue by changwu** [ashishlahoti/hugo-theme-highway#5]
hi, i meet a problem again.
config.toml:
```
[Site]
disqusShortname = "XXXXXXXX" # Enable Disqus comments by entering your Disqus shortname

[Params]
comments = true

```
and in ****.md file
```
comments: true

```

but no disqus show in the post page, I check htm code in Chrome, there isn't disqus's anything.
why?? need you help.

**Comment by ashishlahoti** [comment]
Hi,

Please take the latest from github. I have fixed the issue :)

Thanks,
Ashish

**Comment by changwu** [comment]
Thank u
