### ISSUE TITLE
Why script of google adense hasn't double quote(")

### ISSUE THREAD

**Issue by changwu** [ashishlahoti/hugo-theme-highway#6]
hi, in html's head, I find script like:
```
<script data-ad-client=ca-pub-6935232101088714 async src=https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js></script>
```
I check patrial of google_adsense.html, it looks well with double quote.
```
{{- with .Param "googleAdsense" -}}
<script data-ad-client="{{ . }}" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
{{- end -}}
```
Why? Would it cause no google adsense?

**Comment by ashishlahoti** [comment]
Hi Changwu,

I tested the hugo-theme-highway and I can see this in my html:- 

```
<script data-ad-client="ca-pub-XXXXXXXXXXXXX" async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
```

I am not sure about your issue. It might be due to different version of Hugo. I have tested it with below version:-
```
% hugo version
hugo v0.81.0+extended darwin/amd64 BuildDate=unknown
```

Thanks,
Ashish

**Comment by changwu** [comment]
local I use 0.82.1, no adense scripts, in my site on netlify, I use 0.83.1:
```
<meta name=generator content="Hugo 0.83.1">
```
Thanks.
