### ISSUE TITLE
authors page display nothing and author page 404

### ISSUE THREAD

**Issue by changwu** [ashishlahoti/hugo-theme-highway#7]
hi, I have set up my first hugo site, thanks for your great share.
but I find that authors page display nothing and author page 404, do you have time to check it ?
Hugo is great, highway theme is wonderful.

**Comment by ashishlahoti** [comment]
Updated the examples to display authors in /authors url. You need to add `authors` taxonomy on each blog page in frontmatter.

check this commit:-
https://github.com/ashishlahoti/hugo-theme-highway/commit/d24e8034d8d58e41c91ed2cac842c6d9662f0c1c

**Comment by changwu** [comment]
Thanks for your great example, I have get it about authors page.
